### ISSUE TITLE
mouse control of 1D scale not working

### ISSUE THREAD

**Issue by mpfoster** [onemoonsci/nmrfxprocessorgui#23]
when processing a 1D vector, the mouse scroll wheel alters vertical offset. same w/ shift-scroll and command-scroll. option(alt)-scroll changes view window.

control-scroll used to change the vertical scale of the 1D vector. now, it exhibits unexpected behavior and seems to invert and lower the vertical scale, regardless of scroll direction.

Analyst 10.3.85, MacOS

**Comment by brucejohnson** [comment]
Fixed in 10.3.86
